changesDir: .changes
unreleasedDir: unreleased
headerPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
fragmentFileFormat: '{{.Time.Format "20060102T150405"}}'

kinds:
  - label: feature
    auto: minor
  - label: fix
    auto: patch
  - label: improvement
    auto: minor

custom:
  - key: Platform
    label: Platform
    type: enum
    enumOptions:
      - all
      - android
      - ios
